<a href="https://colab.research.google.com/github/mhtattersall/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# !pip install numpy
import numpy as np

In [2]:
# creating arrays
# only 1 data type allowed in numpy arrays
a = np.array([1,2,3], dtype=int) # 1D array or vector
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) # 2D array or matrix
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2.5,1), (4,5,6)]], dtype=float) # 3D array or tensor
print("ID array:",a)
print("2D array:",b)
print("3D array:",c)
my_list = [1,-2,3,5]
my_array = np.array(my_list) # convert a list into an array
# np.array() converts a list, tuple or an array-like object to an array
print(my_array)
print(type(my_array))

ID array: [1 2 3]
2D array: [[1.5 2.  3. ]
 [4.  5.  6. ]]
3D array: [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.5 1. ]
  [4.  5.  6. ]]]
[ 1 -2  3  5]
<class 'numpy.ndarray'>


In [3]:
# 0-dim arrays, or scalars, are the elements in an array.
# np.array(42) # create a 0-dim array with a single scalar.  Note only use parentheses.

In [4]:
# initial placeholders
f = np.zeros((3,4)) # create an array of zeros
g = np.ones((2,3,4),dtype=np.int16) # create an array of ones
h = np.arange(10,25,5) # create an array of evenly spaced values (step value)
i = np.linspace(0,2,9) # create an array of evenly-spaced values over a specified range (number of samples)
j = np.full((2,2),7) # create a constant array
k = np.eye(2) # create a 2X2 identity matrix, eye gives more options than identity method
l = np.identity(3) # creates a 3x3 identity matrix
m = np.random.random((2,2)) # create an array of a given shape with random values between 0 (inclusive) and 1 (exclusive) # same as np.random.rand
mm = np.random.random((2,2))*10 # as above, but random values between 0 (inclusive) and 10 (exclusive)
n = np.empty((3,2)) # create an empty array
o = np.random.uniform(low=1,high=3,size=(2,3)) # generate a random values in a specified interval to a specified size
rng = np.random.default_rng() # create a default random number generator, this is an API and is recommemded for samples
p = rng.random(size=(2,3)) # call the random number generator
q = np.random.choice([0,1],size=20) # create an array with a random sample from a given 1-D array, ints by default
r = np.random.choice(np.arange(10,20,2),20) # create an array with 20 numbers from a random sample of 10,12,14,16,18
s = np.random.randint(0, 5, (3, 4)) # a random choices of ints from 0 (inclusive) to 5 (exclusive) in a given array shape
t = np.random.randn(5) # generate 1x5 random numbers from a standard normal distribution (mean 0, standard deviation 1)
u = np.random.ranf(size=(5,4)) # create a 5x4 matrix with random floats in the half open interval [0.0,1.0)
v = np.random.normal(1, 2, (3, 4))  # Creates a 3x4 array of random samples from a normal distribution with mean 1 and sd 2.
# np.random.seed(0) # set random seed for replication of data (otherwise random numbers based on current time)
print("3x4 array of zeros:",f)
print("2x3x4 arrrays of ones",g)
print("evenly-spaced values from 10 to 25 (exclusive) with step of 5:",h)
print("evenly-spaced values from 0 to 2 (inclusive) with 9 elements:",i)
print("2x2 arrays of constants:",j)
print("2x2 identity matrix",k)
print("3x3 identity matrix",l)
print("2x2 array of random values between 0 (inclusive) and 1 (exclusive):",m)
print("2x2 array of random values between 0 (inclusive) and 10 (exclusive):",mm)
print("3x2 empty array:",n)
print("2x3 matrix with random values between 1 and 3:",o)
print("2x3 matrix with numpy API random number generator:",p)
print("a random sample of 0 or 1 over 20 times:",q)
print("a random sample from an array from 10 to 20 (exclusive), with a stride of 2, 20 times:",r)
print("3x4 matrix with a random sample of ints from 0 to 4:",s)
print("a random sample of 5 numbers from a standard normal distribution:",t)
print("5x4 matrix with random floats between 0 (inclusive) and 1 (exclusive):",u)
print("a random sample in a 3x4 matrix from a specified normal distribution:",v)

3x4 array of zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2x3x4 arrrays of ones [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
evenly-spaced values from 10 to 25 (exclusive) with step of 5: [10 15 20]
evenly-spaced values from 0 to 2 (inclusive) with 9 elements: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
2x2 arrays of constants: [[7 7]
 [7 7]]
2x2 identity matrix [[1. 0.]
 [0. 1.]]
3x3 identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2x2 array of random values between 0 (inclusive) and 1 (exclusive): [[0.94587156 0.03488253]
 [0.12853863 0.39130659]]
2x2 array of random values between 0 (inclusive) and 10 (exclusive): [[2.79379716 9.60883081]
 [3.67813039 1.80780689]]
3x2 empty array: [[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]
2x3 matrix with random values between 1 and 3: [[2.28836757 2.36920081 2.72183156]
 [1.07578427 1.63258422 1.02056632]]
2x3 matrix with numpy API random number generator: [[0.42511631 0.17354668 0.85522167]
 [0.1548924  0.70314

In [ ]:
# saving and loading on disk
# np.save('my_array.npy', a) # saves a NumPy array 'a' to a file named 'my_array.npy' i.e. a binary file in .npy format in the current working directory
# loaded_array = np.load('my_array.npy') # load the array from the file
# np.savez('array.npz', a, b) # saves multiple arrays into a single file in compressed .npz format
# loaded_data = np.load('array.npz') # Load the arrays from the file
# Access the arrays using their variable names:
# loaded_a = loaded_data['a']
# loaded_b = loaded_data['b']
# Print the loaded arrays:
# print("Loaded 'a':\n", loaded_a)
# print("\nLoaded 'b':\n", loaded_b)

In [ ]:
# np.loadtxt("myfile.txt",delimiter=",") # saving and loading text files
# this assume the data in the text file is formatted so it can be interpreted as a 2D array
# each line in the text file corresponds to a row in the array
# values on each line should be separated by a delimiter (whitespace is default)
# np.genfromtxt("my_file.csv", delimiter= ',') # similar to np.loadtext, this can handle missing value, different data types and more complex data structures
# np.savetxt( "myarray.txt", a, delimiter= " ") # saves an array to a text file

In [ ]:
# inpsecting arrays
# np.info(b) # prints array info: class, shape, strides, itemsize, aligned, contiguous, fortran, data pointer, byteorder, byteswap
# b.shape # tuple of array dimensions
# print(len(a)) # length of 1D array
# c.ndim # number of array dimensions or axes
# c.size # number of array elements
# b.dtype  # data type of array elements
# a.dtype.name  # name of data type
# a.astype(int) # convert an array to a different type, arrays only accept the same data types

In [ ]:
# data types
# np.int64 # signed 64-bit integer types
# np.float32 # standard double-precision floating point
# np.complex # complex numbers represented by 128 floats
# np.bool # boolean type storing TRUE and FALSE values
# np.object # python object type
# np.string_ # fixed-length string type
# np.unicode_ # fixed-length unicode type

In [3]:
# arithmetic operations and aggregate functions
# we can also pass lists to some of these functions
# artihmetic operations are elementwise, so if performing operations with 2 arrays they must be the same shape or be capabale of being broadcast to same shape
# Example: (broadcasting)
large = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
small = np.array([10, 20, 30])
result = large + small
print(result)
# this allows arithmetic operations to be performed with a scalar (see below)
# Further example:
aa = np.ones(10)
aa[:] = 2 # creates a slice, which is a view, not a copy (see below)
print(aa)
x = np.array([2,3,4])
y = np.array([4,6,-1])
# z = x - y # subtraction
# z = np.subtract(x,y)
# z = x + y # addition
# z = np.add(x,y)
# z = x / y # division
# z = np.divide(x,y)
# z = x * y # multiplication
# z = np.multiply(x,y)
# z = np.exp(x) # elementwise exponential function
# z = np.sqrt(x) # elementwise square root
# z = np.sin(x)  # elementwise sine, input array in radians ie. np.pi
# z = np.cos(x) # elementwise cosine. input array in radians ie np.pi
# z = np.log(x) # elementwise natural logarithm
# z = x.dot(y.T) # dot product of x,y - inner dimensions must match
# z = np.power(x,2) # elementwise to specified power
# z = x ** y # elementwise power
# z = x.sum() # arraywise sum
# z = x.min() # arraywise minimum value
# z = b.max(axis=1) #arraywise maximum value axis=1 is along rows, axis=0 is along cols
# z = x.argmax() # returns index position of max value
# z = x.cumsum() #arraywise cumulative of elements
# z = x.mean() # arraywise mean
# z = np.median(x) # arraywise median
# z = np.std(x, ddof=1) # arrayswise sample standard deviation, population sd is ddof=0
# z = x * 1.5 # multiply all elements with a scalar
# z = x + 1.1 # adds to all elements and makes them floats
# z = np.abs() # retuns the absolute number of each element
# z = np.ceil() # increments every float element to the next highest integer
# z = np.floor() # increments every float element to the next lowest integer

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [6]:
# array comparison
# x == y # elementwise comparison, returns booleans
# x < 2 # elementwise comparison, returns booleans
# np.array_equal(x, y) # arraywise comparison

In [7]:
# views and copying arrays
b = a[0:2] # slicing creates a view, not a copy (different behaviour to lists)
b = a.view() # create a view of the array with the same data
# view doesn't create a new copy, it creates a new array variable object that references the same data in memory.
# modifying a view also modifies the original array
b = np.copy(a) # create a deep copy of the array
# copy creates a new memory reference with its own data
# print(id(a),id(b)) # to check memory references

In [4]:
# index and slicing (slicing creates a view - see above)
a = np.array([1,-2,5]) # 1D array
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) # 2D array
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2.5,1), (4,5,6)]], dtype = float) # 3D array
# d = a[2].copy() # select the element at index 2 and create a new object in memory
# a[:] = 2 # select all and broadcast all elements to the value 2
# a[-2] # select last second last element
# a[-2:] # select last 2 elements
# a[1:] # select all elements except the first
# a[0:2] # select elements at index 0 (inclusive) to index 2 (exclusive)
# b[1][0] # select element at row 1, col 0
# b[1,0] # select element at row 1, col 0
# c[1][0][1] # select element at dim 1, row 0, col 1
# c[1,0,1] # select element at dim 1, row 0, col 1
# b[0:2,1] # select elements at rows 0 and 1 in column 1
# b[:1] # select elements in row 0
# b[0] # select row 0
# b[1] # select row 1
# b[:,0] # select elements in col 0
# b[:,1] # select elemments in col 1
# b[:,-1] # select elemments in last col
# b[:,[0, 2]] # select first and third columnns
# c[1,...] # select elements in dim 1
# a[::-1] #reverse an array
# b[[1,0,1, 0],[0,1, 2, 0]]  # select with coordinates for rows and cols i.e (1,0),(0,1),(1,2) and(0,0)
# b[[1,0,1, 0]][:,[0,1,2,0]] # select a subset of the matrix rows and columns
# the first part selects rows, second part selects cols, returns a 4x4 array


In [10]:
# conditionals (masks)
# d = a<0 # select elements less than 0, returns a boolean array (a<2 is a boolean mask)
# assign the mask as a variable and pass this as a filter mask1 = a<0, negative = a[mask1]
# can create multiple filtering masks and use bitwise operators & (AND)|(OR)~(NOT)
# z[a<0] returns an array (not a boolean) which meets the conditional
# a[mask1|mask2] returns an array (not a boolean) which meets either filter
# Example:
mask1 = a<0
mask2 = a>4
d = a[mask1|mask2]
print(d)

array([-2,  5])

In [11]:
# array manipulation
# arrays are mutable objects
# a[0] = -2 # assign a new value to the first element
# a[2,3] = np.NaN # assign element at index to be 'Not a Number'
# a[1:] = 2 # change all elements after the first to 2 (broadcasting)
# d = a.copy() # copy an array to create a new object in memory, otherwise changes are inplace (different to lists)
a = np.array([1,2,-3])
b = np.array([(1.5,2,3), (4,1,6)], dtype = float)
# c = np.transpose(b) # transpose
# c = b.T # transpose
# c = b.ravel() # flatten the array to 1D, without creating a new memory reference
# c = b.flatten() # flatten the array to 1D, and creates a new memory reference
# c = b.reshape(3, -2) # reshape to 3x2, doesn’t change data, -2 tells numpy to automatically calculate the size of the second dimension
# a.resize(3,1) # resizes the array inplace of the original
# c = np.insert(a,1,5) # insert the value 5 at index 1
# c = np.delete(a,[1]) # delete the item at index 1
# c = a[np.newaxis,:] # add a new dim or axis to an array
# c = np.expand_dims(a, axis=0) # add a new dim or axis to an array
# a.sort() # sort an array inplace, doesn't create a new memory object
# b.sort(axis=0) # sort the elements of an array on row axis inplace
# a.round(2) # round each element to 2 decimal places
# Example: (quickly create a 2-dim array)
c = np.arange(0,9)
d = c.reshape(3,3)
print(d)
# Example: (add a shorter to a longer using a for loop and empty_like())
array_a = np.array([(0,0,0),(1,1,1),(2,2,2),(3,3,3)])
array_b = np.array([1,1,-1])
answer = np.empty_like(array_a)
for i, row in enumerate(array_a):
    print(i,row)
    answer[i] = row + array_b
print(answer)
# Example: (create a checkerboard)
z = np.zeros((8,8), dtype=int)
z[1::2, ::2] = 1 # slice each row starting at 1, stride 2 and assign the values to 1
z[::2, 1::2] = 1 # slice each col starting at 1, stride 2 and assign values to 1
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0 [0 0 0]
1 [1 1 1]
2 [2 2 2]
3 [3 3 3]
[[ 1  1 -1]
 [ 2  2  0]
 [ 3  3  1]
 [ 4  4  2]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
# combining and splitting arrays
a = np.array([1,2,3]) # 1D array
b = np.array([(1.5,2,3),(4,5,6)], dtype = float) # 2D array
c = np.array([(7,8,9),(-1,-2,-3)], dtype = float)
d = np.array([(1.5,2,3,-1),(4,5,6,-2)], dtype = float) # 2D array
# e = np.append(b,a) # concatenate 2 arrays, resulting in a new flattened array
# e = np.concatenate((b,c),axis=0) # concatenate arrays with matching dimensions to create a new array, specify axis to concatenate along axis=0 is rows, axis=1 is cols
# e = np.vstack((b,c)) # stack arrays vertically (row wise)
# np.r_[b,c] # stack arrays vertically (row wise)
# e = np.hstack((b,c)) # stack arrays horizontally (column wise)
# e = np.column_stack((b,c)) # create stacked column wise arrays
# e = np.c_[b,c] # create stacked column wise arrays
# splitting arrays
# e,f = np.hsplit(d,2) # split the array horizontally into 2 sub arrays
# e,f = np.vsplit(d,2) # split the array vertically into 2 sub arrays

In [13]:
# np.where() and np.extract() are used for conditional operations on arrays
# np.where() returns element index
# np.extract() returns the element
# Example:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
indices = np.where(arr_2d > 5) # Use np.where to find the indices where a condition is met
print("index arrays:",indices) # the values greater than 5 in the 2D array are found at the positions (1,2), (2,0), (2,1) and (2,2)
values_at_indices = arr_2d[indices] # Access the values at those indices
print("values at indices:",values_at_indices)
extracted_values = np.extract(arr_2d > 5, arr_2d)
print("extracted values:",extracted_values)
# Example: (delete with reference to indices)
arr_1d = np.array([0,0,0,2,4,6,6])
indices = np.where(arr_1d == 0)
answer = np.delete(arr_1d,indices)
print(answer)

index arrays: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
values at indices: [6 7 8 9]
extracted values: [6 7 8 9]
[2 4 6 6]


In [19]:
# payback period with np.where()
cf = np.array([-200,20,50,70,100,50]) # array of cashflows
# np.where(cf.cumsum() >0) # calculate cumsum on the cf array, and identify the index positions which satisfy the condition >0
# np.where(cf.cumsum()>0)[0][0] # identify the first index position where cumsum is positive. Second [0] indicates first index position
np.where(cf.cumsum()>0, "Break-even","Not break-even") # return strings if condition met, or if condition not met

array(['Not break-even', 'Not break-even', 'Not break-even',
       'Not break-even', 'Break-even', 'Break-even'], dtype='<U14')

In [15]:
# npv using arrays
cf = np.array([-200,20,50,70,100,50]) # array of cashflows
r = 0.06
f = 1 + r
n = np.arange(0,6)
pv_array = cf/f**n
npv = pv_array.sum()
npv

38.71337130837991